export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIES_NAME = "GET_COUNTRIES_NAME";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const GET_ACTIVITIES = "GET_ACTIVITIES";

export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";
export const FILTER_BY_CONTINENTS = "FILTER_BY_CONTINENTS";
export const FILTER_BY_ACTIVITIES = "FILTER_BY_ACTIVITIES";
export const RESET_FILTERS = "RESET_FILTERS";
